### ISSUE TITLE
This package cannot be installed on non-English windows systems

### ISSUE THREAD

**Issue by moe001** [bubblesub/ass_tag_parser#5]
```
PS C:\xxx> pip install ass-tag-parser
Collecting ass-tag-parser
  Using cached https://xxx/ass_tag_parser-2.3.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-1s17sz2y\\ass-tag-parser\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-1s17sz2y\\ass-tag-parser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-7kr7ks__'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-1s17sz2y\ass-tag-parser\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-1s17sz2y\ass-tag-parser\setup.py", line 11, in <module>
        long_description=(Path(__file__).parent / "README.md").read_text(),
      File "c:\python38\lib\pathlib.py", line 1236, in read_text
        return f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 601: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

There are different default encodings in these operating systems (for `open` etc.)

**Comment by rr-** [comment]
Fixed in 2.3.1
